server:
  port: 8800

# MP日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
  mapper-locations: classpath:com/qingfeng/electronic/modules/**/mapper/*.xml

spring:
  servlet:
    multipart:
      # 设置最大上传文件大小
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/general_auth?rewriteBatchedStatements=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      max-lifetime: 1800000 # 设置连接的最大生命周期，单位为毫秒，根据实际情况调整

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    password:
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 阿里云OOS
aliyun:
  oss:
    endpoint:
    accessKeyId: 
    secret: 
    bucket: 